### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Exorcism0666** [Glazelf/NinigiBot#107]
**Describe the solution you'd like**

Why not add in the parameters a command which would allow to change the language of Ninigi, for example: in French, Spanish, Chinese etc ...

**Describe alternatives you've considered**

seeing that I am French I could help you if you want hehe (if you want to add this option of course)

DoD (added here and maintained by Glaze so it shows up in Issues list):
- [ ] Put all English responses in a `json` file.
- [ ] Readjust code everywhere to accomodate for language setup.
- [ ] Move all commands
- [x] Move all events
- [x] Move all affairs
- [x] Move all other guild-specific text
- [x] Read from `json` file correctly.
- [x] Load all language strings on boot so that they don't have to be loaded every time a command is used.
- [x] Get correct language set in message event, pass through to command to avoid code repetition.
- [x] Add language per server to database.
- [x] Make command to swap between different language files, preferably adaptively based on the file name. (example: `?language jp` reads `jp.json`)
- [x] Variables: `let string = string.replace('[0]', variable);`?
- [x] Default to English if no language is set
- [x] Default to English string if string is missing from that specific language.
- [x] Find a good way for people to contribute.
Look into https://poeditor.com/projects/view?id=444591 & ~~https://crowdin.com/~~
- [ ] Make Pokémon command get different language API responses.
- [ ] Translate Shinx commands.
- [ ] If message is ephemeral use user's locale, otherwise use guild's language, replacing `?language` command.

**Comment by Glazelf** [comment]
> Why not add in the parameters a command which would allow to change the language of Ninigi, for example: in French, Spanish, Chinese etc ...  

Would be quite a big task since I would need to make language files for every supported language but not impossible for sure.
I don't know if I could easily translate all the command names like `?togglechannel` to all languages without messing up the code but just the responses Ninigi seems back should be possible.

> seeing that I am French I could help you if you want hehe (if you want to add this option of course)  

I only speak Dutch, which is a translation noone needs, so for other languages I would need others to translate instead yeah lmao

DoD:
- [ ] Put all English responses in a file (`.json`?) and read from it correctly.
- [ ] Make command to swap between different language files, preferably adaptively based on the file name. (example: `?language jp` reads `jp.json`)
- [ ] Default to English if string is missing.
- [ ] Find a good way for people to contribute.

**Comment by Glazelf** [comment]
Slash commands will get new localization options soon, at which point most of this can likely be redone aside from the actual translations. Cool.

**Comment by Glazelf** [comment]
This entire issue will likely have to restart development due to slash command support and the slash command language support beta.
One day. Maybe.

**Comment by Glazelf** [comment]
Closing this for now as I would have to restart development anyways. Might get back to this and will just make a new, clean issue for it.
