### ISSUE TITLE
Track voice activity

### ISSUE THREAD

**Issue by RubenVerhoev** [Glazelf/NinigiBot#68]
Track voice activity zodat we ook zo munten kunnen harken en vergokken

https://stackoverflow.com/questions/52012882/how-to-get-the-time-spent-speaking-in-a-voice-channel

**Comment by Glazelf** [comment]
https://github.com/Glazelf/NinigiBot/commit/6bb602e8c29ea31c6adbc881e69dbb1e489a8ab8
`voiceStateUpdate` doesn't log a user specific event, instead it logs the client and guild state at the different intervals.
Because of this it's basically useless for trying to time and log VC joins/leaves without further research into vc events (would require a listener for every user to hand out money based on activity time anyways)
